targets:
  $default:
    builders:
      json_serializable:
        options:
          # Generate a copy of the model class with the `toJson` method included.
          include_if_null: false
          explicit_to_json: true
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          field_rename: snake
      injectable_generator:
        options:
          auto_register: true
          class_name_pattern: ""