# Generated by Django 5.0.6 on 2026-05-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioLiturgico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Una sola fila por día.', unique=True, verbose_name='Fecha litúrgica')),
                ('tipo_celebracion', models.CharField(choices=[('feria', 'Feria'), ('memoria_libre', 'Memoria libre'), ('memoria_obligatoria', 'Memoria obligatoria'), ('fiesta', 'Fiesta'), ('solemnidad', 'Solemnidad'), ('domingo', 'Domingo')], default='feria', max_length=24)),
                ('color_liturgico', models.CharField(choices=[('blanco', 'Blanco'), ('rojo', 'Rojo'), ('verde', 'Verde'), ('morado', 'Morado'), ('rosa', 'Rosa'), ('dorado', 'Dorado'), ('negro', 'Negro')], default='verde', max_length=12)),
                ('titulo', models.CharField(blank=True, help_text='Ej: "III Domingo del Tiempo Ordinario", "San Juan Bautista".', max_length=255)),
                ('primera_lectura_cita', models.CharField(blank=True, max_length=120)),
                ('primera_lectura_texto', models.TextField(blank=True)),
                ('salmo_cita', models.CharField(blank=True, max_length=120)),
                ('salmo_respuesta', models.CharField(blank=True, max_length=255)),
                ('salmo_texto', models.TextField(blank=True)),
                ('segunda_lectura_cita', models.CharField(blank=True, max_length=120)),
                ('segunda_lectura_texto', models.TextField(blank=True)),
                ('aclamacion_evangelio', models.TextField(blank=True, help_text='Aleluya / Versículo antes del Evangelio.')),
                ('evangelio_cita', models.CharField(blank=True, max_length=120)),
                ('evangelio_texto', models.TextField(blank=True)),
                ('reflexion', models.TextField(blank=True)),
                ('fuente', models.CharField(blank=True, help_text='URL o nombre de la fuente desde la que se importó.', max_length=120)),
                ('importado_en', models.DateTimeField(blank=True, null=True)),
                ('editado_manualmente', models.BooleanField(default=False, help_text='Si está marcado, el proxy NO sobrescribirá esta fila.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calendario Litúrgico',
                'verbose_name_plural': 'Calendario Litúrgico',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='core_liturg_fecha_6ad50b_idx'), models.Index(fields=['color_liturgico'], name='core_liturg_color_l_9414e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntencionOracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Opcional. El fiel puede enviarla anónima.', max_length=120)),
                ('contacto', models.CharField(blank=True, help_text='Email o teléfono — opcional, solo para seguimiento privado.', max_length=120)),
                ('intencion', models.TextField(help_text='Texto de la petición / acción de gracias.')),
                ('es_anonima', models.BooleanField(default=True)),
                ('es_publica', models.BooleanField(default=False, help_text='Si está marcada, puede mostrarse en el muro público de la app.')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_oracion', 'En oración'), ('atendida', 'Atendida'), ('descartada', 'Descartada (spam/ofensiva)')], default='pendiente', max_length=16)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intención de Oración',
                'verbose_name_plural': 'Intenciones de Oración',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['-creado_en'], name='core_liturg_creado__de87fa_idx'), models.Index(fields=['estado'], name='core_liturg_estado_c243bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='MisaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(default='Templo Principal', help_text='Templo Principal, Capilla, Adoración, etc.', max_length=120)),
                ('celebrante', models.CharField(blank=True, help_text='Opcional. Si rota semana a semana, dejar vacío.', max_length=120)),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horario de Misa',
                'verbose_name_plural': 'Horarios de Misas',
                'ordering': ['dia_semana', 'hora'],
                'indexes': [models.Index(fields=['dia_semana', 'hora'], name='core_liturg_dia_sem_0dacb4_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoMisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_evento', models.DateTimeField(help_text='Inicio programado o real de la transmisión.')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_vivo', 'En vivo'), ('grabada', 'Grabada'), ('cancelada', 'Cancelada')], default='programada', max_length=12)),
                ('url_facebook', models.URLField(help_text='URL de la publicación o transmisión en Facebook.', max_length=500)),
                ('facebook_video_id', models.CharField(blank=True, help_text='ID del video en Facebook (para embed).', max_length=64)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbs/')),
                ('duracion_minutos', models.PositiveIntegerField(blank=True, help_text='Llenar cuando ya esté grabada.', null=True)),
                ('destacada', models.BooleanField(default=False, help_text='Mostrar como destacada en el home de Flutter.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video de Misa',
                'verbose_name_plural': 'Videos de Misas',
                'ordering': ['-fecha_evento'],
                'indexes': [models.Index(fields=['-fecha_evento'], name='core_liturg_fecha_e_dd7c57_idx'), models.Index(fields=['estado'], name='core_liturg_estado_3972ba_idx')],
            },
        ),
    ]
