# Generated by Django 5.0.6 on 2026-05-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_liturgia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=30)),
                ('lugar', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('liturgia', 'Liturgia'), ('comunidad', 'Comunidad'), ('juventud', 'Juventud'), ('formacion', 'Formación'), ('mision', 'Misión')], default='comunidad', max_length=20)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('es_recurrente', models.BooleanField(default=False)),
                ('frecuencia_recurrencia', models.CharField(blank=True, max_length=120, null=True)),
                ('maximo_participantes', models.PositiveIntegerField(blank=True, null=True)),
                ('participantes_actuales', models.PositiveIntegerField(default=0)),
                ('requiere_inscripcion', models.BooleanField(default=False)),
                ('contacto_responsable', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('etiquetas', models.JSONField(blank=True, default=list)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='OficinaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=120)),
                ('horarios', models.JSONField(blank=True, default=dict)),
                ('servicios', models.JSONField(blank=True, default=list)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Información de Oficina',
                'verbose_name_plural': 'Información de Oficina',
            },
        ),
        migrations.CreateModel(
            name='ParroquiaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Parroquia Cristo Resucitado', max_length=120)),
                ('historia', models.TextField(blank=True)),
                ('mision', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('valores', models.JSONField(blank=True, default=list)),
                ('imagenes', models.JSONField(blank=True, default=list)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=120)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Información Parroquial',
                'verbose_name_plural': 'Información Parroquial',
            },
        ),
        migrations.CreateModel(
            name='Santo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('titulo', models.CharField(blank=True, max_length=180)),
                ('fecha_celebracion', models.DateField(help_text='Día y mes de la celebración (el año se puede ignorar o usar el actual).')),
                ('biografia', models.TextField(blank=True)),
                ('festividad', models.CharField(blank=True, max_length=120)),
                ('patrono', models.CharField(blank=True, max_length=120)),
                ('oracion', models.TextField(blank=True)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('atributos', models.JSONField(blank=True, default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Santo',
                'verbose_name_plural': 'Santos',
                'ordering': ['fecha_celebracion'],
            },
        ),
    ]
