# Generated by Django 5.0.6 on 2026-05-26 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_liturgia', '0002_evento_oficinainfo_parroquiainfo_santo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('categoria', models.CharField(choices=[('lectio_divina', 'Lectio Divina'), ('liturgia_horas', 'Liturgia de las Horas'), ('rosario', 'Santo Rosario'), ('coronilla', 'Coronilla'), ('basicas', 'Oraciones Básicas'), ('intenciones', 'Oraciones por Intención'), ('novenas', 'Novenas')], default='basicas', max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('contenido', models.TextField(blank=True, help_text='Contenido de la oración si es de texto simple.', null=True)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('destacada', models.BooleanField(default=False)),
                ('duracion_estimada', models.PositiveIntegerField(default=5, help_text='Duración estimada de la oración en minutos.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oración',
                'verbose_name_plural': 'Oraciones',
                'ordering': ['categoria', 'orden', 'titulo'],
                'indexes': [models.Index(fields=['categoria'], name='core_liturg_categor_071272_idx'), models.Index(fields=['slug'], name='core_liturg_slug_03fe60_idx'), models.Index(fields=['activo'], name='core_liturg_activo_d07518_idx'), models.Index(fields=['destacada'], name='core_liturg_destaca_255e22_idx')],
            },
        ),
        migrations.CreateModel(
            name='OracionSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('oracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='core_liturgia.oracion')),
            ],
            options={
                'verbose_name': 'Sección de Oración',
                'verbose_name_plural': 'Secciones de Oraciones',
                'ordering': ['orden'],
            },
        ),
    ]
