# Generated by Django 5.0.6

import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('core_liturgia', '0003_oracion_oracionseccion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.CheckConstraint(
                check=Q(participantes_actuales__gte=0),
                name='evento_participantes_no_negativos',
            ),
        ),
        migrations.CreateModel(
            name='EventoInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participante_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('notas', models.CharField(blank=True, max_length=500)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core_liturgia.evento')),
            ],
            options={
                'verbose_name': 'Inscripción a evento',
                'verbose_name_plural': 'Inscripciones a eventos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventoinscripcion',
            constraint=models.UniqueConstraint(
                condition=~Q(idempotency_key=''),
                fields=('evento', 'idempotency_key'),
                name='evento_idempotencia_unica',
            ),
        ),
    ]
